!function(){function e(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:250;!function n(){document.querySelector("#onetrust-pc-sdk")&&"u">typeof OneTrust?e():setTimeout(n,t)}()}function t(t){e(function(){var e,n,o,r=document.querySelector("#onetrust-pc-sdk");"none"===window.getComputedStyle(r).display&&OneTrust.ToggleInfoDisplay(),e=t,n=document.getElementById("onetrust-pc-sdk"),new MutationObserver(function(t,o){t.some(function(e){return"style"===e.attributeName})&&"none"===n.style.display&&(e.focus(),o.disconnect())}).observe(n,{attributes:!0,childList:!1,subtree:!1}),null==(o=document.querySelector("#lulu-ot-dsar-form-iframe"))||o.remove()})}function n(e){window.location.href.toLowerCase().includes("showprivacycenter")&&(t(),e&&window.history.back())}e(function(){var e,t,n,o;(function(){var e,t,n={label:(document.documentElement.getAttribute("lang")||"").startsWith("fr")?"Formulaire de refus":"Opt-out Form",href:"/dns-form",iframeUrl:"https://privacyportal.onetrust.com/webform/b5ce4b51-ea0c-47e5-b855-c12d511f57c9/25f3c2a0-68f7-409e-bd73-676617fc3c93",container:document.querySelector("#ot-desc-id-TAB02")};function o(e){var t=document.createElement("template");return t.innerHTML=e,t.content||t}document.querySelector("#lulu-ot-opt-out-link")||(null==(e=n.container)||e.append(o(`
             <a href="${n.href}" target="_blank" id="lulu-ot-opt-out-link">
                 ${n.label}
             </a>
        `)),null==(t=document.querySelector("#lulu-ot-opt-out-link"))||t.addEventListener("click",function(e){var t;e.preventDefault(),null==(t=document.querySelector("#onetrust-pc-sdk"))||t.append(o(`
                  <iframe
                          id="lulu-ot-dsar-form-iframe"
                          src="${n.iframeUrl}"
                          style="border: none; position: absolute; width: 100%; height: 100%; z-index: 99; left: 0; top: 0;"
                  ></iframe>
              `)),window.addEventListener("message",function(e){var t=e;console.debug("[Privacy] dnsFormMessageHandler",t);var n=function(e){if("string"==typeof e)try{return JSON.parse(e)}catch(e){}return null}(t.data);if(Array.isArray(null==n?void 0:n.requestTypes)&&"Do Not Share My Personal Information"===n.requestTypes[0]){if(window.location.pathname.endsWith("/privacy-preference-center.html")){var o=document.getElementById("confirmation-message"),r=document.getElementById("privacy-confirmation-header"),c=document.getElementById("privacy-confirmation-text");o&&(o.style.display="block",r.textContent="Return to the lululemon app to continue your journey.",c.style.display="none")}setTimeout(function(){console.debug("[Privacy] Calling OneTrust.RejectAll()"),OneTrust.RejectAll()},3e3)}})}))})(),window.location.pathname.endsWith("/privacy-preference-center.html")?null==(e=document.querySelector("#ot-header-id-TAB02"))||e.click():null==(t=document.querySelector("#ot-header-id-TAB01"))||t.click(),window.location.pathname.endsWith("/privacy-preference-center.html")&&document.querySelector("button.save-preference-btn-handler").addEventListener("click",function(e){document.getElementById("confirmation-message").style.display="block"}),n=document.querySelector(".privacy-notice-link"),o=document.querySelector("#ot-desc-id-TAB01 .ot-category-desc"),n&&o&&o.appendChild(n)}),document.addEventListener("click",function(e){var n,o=e.target.closest("a"),r=(null==o||null==(n=o.href)?void 0:n.toLowerCase())||"";(r.includes("/ca-do-not-sell")||r.includes("#showprivacycenter"))&&(e.preventDefault(),t(o))}),n(!1),window.addEventListener("hashchange",function(){return n(!0)})}();